name: Build & Publish Debug APK

on:
 push:
  branches:
   - 'develop'
   
jobs:
  config_and_set:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut Code
      uses: actions/checkout@v1
    - name: install despendicia
      run: npm install
    - name: Run test
      run: npm test
jobs: 
  runs-on: ubuntu-latest
  my_word2:
    steps:
      - name: Run app
        run: npm start


      
    