on:
    push:
        branches:
            master:
                jubs:
                    name: CI INSTALL DEV
                    run: npm install
                    name: Run test
                    run: npm test